export const INVALID_REASONS = {
  INVALID_MARGIN: 'INVALID_MARGIN',
  INVALID_WALLET_ADDRESS: 'INVALID_WALLET_ADDRESS',
  CREATED_TIME_TIMEOUT: 'CREATED_TIME_TIMEOUT',
  INVALID_UNIT: 'INVALID_UNIT',
  INVALID_PRICE: 'INVALID_PRICE',
};

export enum UnitContract {
  USDT = 0,
  VNST = 1,
}

export enum InsuranceContractState {
  PENDING = 'PENDING',
  AVAILABLE = 'AVAILABLE',
  CLAIMED = 'CLAIMED',
  REFUNDED = 'REFUNDED',
  LIQUIDATED = 'LIQUIDATED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELED',
  INVALID = 'INVALID',
}

export enum IsuranceContractType {
  CREATE = "CREATED",
  UPDATE_AVAILABLE= "UPDATE_AVAILABLE",
  UPDATE_INVALID = "UPDATE_INVALID",
  REFUND = "REFUND",
  CANCEL = "CANCEL",
  CLAIM = "CLAIM",
  EXPIRED = "EXPIRED",
  LIQUIDATED = "LIQUIDATED"
}


export const RATIO_DIFF_VALID_PRICE = 0.003;

export const MIN_AMOUNT_TRANSFER_BINANCE = 5;
